import type { SiteContent } from "./types";

const ICONS = {
  architecture: "M6 34h28M10 34V14l10-8 10 8v20M16 34V22h8v12",
  interior: "M8 22h24v8H8zM11 30v4M29 30v4M11 22v-6a3 3 0 0 1 3-3h12a3 3 0 0 1 3 3v6",
  permits: "M11 5h13l7 7v23H11zM24 5v7h7M16 20h10M16 25h10M16 30h6",
  maps: "M5 10l10-4 10 4 10-4v24l-10 4-10-4-10 4zM15 6v24M25 10v24",
  supervision:
    "M8 35V9h10v26M18 16h14v19M4 35h32M12 14h2M12 20h2M12 26h2M23 22h4M23 28h4",
  licensed: "M5 14l6 6L23 8",
  model3d: "M14 4l9 5v10l-9 5-9-5V9zM14 14l9-5M14 14v10M14 14L5 9",
  siteVisits: "M4 8h20v14H4zM4 12h20M9 4v6M19 4v6",
  fixedFee: "M8 4h9l5 5v15H8zM17 4v5h5M12 15h6M12 19h6",
};

export const ar: SiteContent = {
  meta: {
    title: "باسم كيال — مهندس معماري",
    description:
      "الخرائط، التراخيص، التصميم المعماري والداخلي في مكتب واحد. من قطعة الأرض حتى البيت الجاهز، مع شخص واحد تتعامل معه.",
  },
  nav: {
    studio: "المكتب",
    services: "الخدمات",
    projects: "المشاريع",
    process: "طريقة العمل",
    contact: "تواصل معنا",
    cta: "احجز استشارة",
    langLabel: "EN",
    langHref: "/en",
    menuLabel: "القائمة",
  },
  brand: { name: "BASIM KAYAL", role: "ARCHITECT" },
  hero: {
    badge: "نستقبل مشاريع جديدة لعام 2027",
    titleLead: "مساحات مرسومة بدقّة، ",
    titleAccent: "مبنيّة لتدوم.",
    subtitle:
      "الخرائط، التراخيص، التصميم المعماري والداخلي في مكتب واحد. من قطعة الأرض حتى البيت الجاهز، مع شخص واحد تتعامل معه.",
    ctaPrimary: "ابدأ مشروعك",
    ctaSecondary: "شاهد أكثر من 240 مشروعًا",
    stats: [
      { value: 18, suffix: "+", label: "سنة خبرة" },
      { value: 240, suffix: "+", label: "مشروع منجَز" },
      { value: 96, suffix: "%", label: "تراخيص من أول تقديم" },
    ],
    model: { tag: "نموذج ثلاثي الأبعاد · فيلا 01", scale: "مقياس 1:100", elev: "الارتفاع +7.20 م", gfa: "المساحة 640 م²" },
    floatCard: {
      title: "فيلا 01",
      floorsLabel: "الطوابق",
      floors: "3",
      plotLabel: "المساحة",
      plot: "1,150 م²",
      permitLabel: "الترخيص",
      permit: "مُعتمَدة",
    },
  },
  marquee: [
    "فلل",
    "مبانٍ سكنية",
    "تصميم داخلي",
    "خرائط مساحية",
    "تراخيص بناء",
    "إشراف هندسي",
  ],
  studio: {
    eyebrow: "المكتب",
    title: "مهندس واحد، من أول رسمة حتى تسليم المفتاح.",
    text: "يصمّم باسم كيال البيوت والمباني من الداخل والخارج، ويتولّى كل ما بين الفكرة والمبنى الجاهز: الخرائط، المخططات، الترخيص والإشراف في الموقع.",
    featured: { tag: "مشروع مميّز", name: "فيلا التلّة", area: "640 م²", floors: "3", year: "2025" },
    cards: [
      { title: "مهندس مرخّص", note: "رقم الترخيص [000000]", icon: ICONS.licensed },
      { title: "3D قبل البناء", note: "تجوّل في كل غرفة", icon: ICONS.model3d },
      { title: "زيارات أسبوعية", note: "مع تقارير مصوّرة", icon: ICONS.siteVisits },
      { title: "أتعاب ثابتة", note: "بلا مفاجآت لاحقًا", icon: ICONS.fixedFee },
    ],
  },
  bigStats: {
    eyebrow: "بالأرقام",
    title: "ثمانية عشر عامًا من المخططات والتراخيص والبيوت الجاهزة.",
    updated: "آخر تحديث [الشهر] 2026",
    stats: [
      { value: 85000, suffix: " م²", label: "مساحة مصمَّمة", note: "بيوت ومبانٍ وتصاميم داخلية" },
      { value: 310, suffix: "+", label: "ترخيص ومعاملة", note: "جُهّزت وتابعناها حتى الموافقة" },
      { value: 1200, suffix: "+", label: "زيارة للموقع", note: "إشراف أسبوعي مع تقارير مصوّرة" },
      { value: 98, suffix: "%", label: "عملاء يعودون أو يوصون بنا", note: "بحسب [استبيان العملاء]" },
    ],
    mix: {
      title: "توزيع المشاريع",
      note: "من أصل 240 مشروعًا",
      rows: [
        { label: "فلل وبيوت خاصة", pct: 54, color: "var(--color-gold)" },
        { label: "مبانٍ سكنية", pct: 21, color: "var(--color-gold-soft)" },
        { label: "تصميم داخلي", pct: 15, color: "var(--color-gold-dust)" },
        { label: "تجاري وعام", pct: 10, color: "#968870" },
      ],
      avgLabel: "متوسط مدة الترخيص",
      avgValue: "11 أسبوعًا",
    },
  },
  services: {
    eyebrow: "الخدمات",
    title: "كل ما يحتاجه مبناك.",
    text: "اختر خدمة واحدة أو المسار كاملًا. كل مرحلة تُجهَّز بحيث تنتقل للتي تليها دون تأخير.",
    timelineLabel: "المدة المعتادة",
    items: [
      {
        num: "01",
        title: "التصميم المعماري",
        text: "فلل وبيوت ومبانٍ، من الرسومات الأولية حتى مخططات التنفيذ الكاملة.",
        items: ["الفكرة الأولية", "مساقط وواجهات", "مناظير 3D", "مخططات تنفيذ"],
        time: "6–12 أسبوعًا",
        icon: ICONS.architecture,
      },
      {
        num: "02",
        title: "التصميم الداخلي",
        text: "توزيع المساحات والمواد والإضاءة والأثاث، مصمَّمة مع المبنى نفسه.",
        items: ["توزيع المساحات", "لوحات المواد", "مخطط الإضاءة", "نجارة خاصة"],
        time: "4–8 أسابيع",
        icon: ICONS.interior,
      },
      {
        num: "03",
        title: "التراخيص وتصاريح البناء",
        text: "تجهيز الملفات وتقديمها للجهات المختصة ومتابعتها حتى الموافقة.",
        items: ["رخصة بناء", "إضافات", "تسوية أوضاع"],
        time: "8–14 أسبوعًا",
        icon: ICONS.permits,
      },
      {
        num: "04",
        title: "الخرائط ومخططات الموقع",
        text: "خرائط مساحية ودراسات للقطعة تُبنى عليها كل القرارات.",
        items: ["خريطة مساحية", "دراسة قطعة", "مخطط موقع"],
        time: "1–3 أسابيع",
        icon: ICONS.maps,
      },
      {
        num: "05",
        title: "الإشراف على البناء",
        text: "زيارات أسبوعية ومتابعة مع المقاولين ليطابق المبنى التصميم.",
        items: ["زيارات أسبوعية", "تقارير مصوّرة", "تسليم"],
        time: "حتى التسليم",
        icon: ICONS.supervision,
      },
    ],
  },
  projects: {
    eyebrow: "أعمال مختارة",
    title: "المشاريع",
    filters: [
      { key: "all", label: "الكل" },
      { key: "residential", label: "سكني" },
      { key: "interiors", label: "داخلي" },
      { key: "commercial", label: "تجاري" },
    ],
    areaLabel: "المساحة",
    floorsLabel: "الطوابق",
    cityLabel: "المدينة",
    yearLabel: "السنة",
    photoPlaceholder: "[صورة المشروع]",
    items: [
      { name: "فيلا التلّة", catKey: "residential", cat: "سكني", city: "[المدينة]", area: "640 م²", floors: "3", year: "2025", hasImage: true },
      { name: "مكتب كيال", catKey: "commercial", cat: "تجاري", city: "[المدينة]", area: "180 م²", floors: "1", year: "2024", hasImage: true },
      { name: "بيت الفناء", catKey: "residential", cat: "سكني", city: "[المدينة]", area: "420 م²", floors: "2", year: "2024", hasImage: false },
      { name: "لوفت حجري", catKey: "interiors", cat: "تصميم داخلي", city: "[المدينة]", area: "210 م²", floors: "1", year: "2025", hasImage: false },
      { name: "شقق بستان الزيتون", catKey: "residential", cat: "سكني", city: "[المدينة]", area: "2,150 م²", floors: "5", year: "2023", hasImage: false },
      { name: "عيادة الأرز", catKey: "commercial", cat: "تجاري", city: "[المدينة]", area: "560 م²", floors: "2", year: "2022", hasImage: false },
    ],
  },
  process: {
    eyebrow: "طريقة العمل",
    title: "طريق واضح في أربع خطوات.",
    badge: "متوسط المشروع: 9 إلى 14 شهرًا",
    steps: [
      { n: "01", time: "الأسبوع 1", title: "الاستشارة", text: "نزور الأرض أو المبنى، نسمع احتياجاتك ونتّفق على النطاق والميزانية والأتعاب." },
      { n: "02", time: "الأسابيع 2–10", title: "الفكرة والتصميم", text: "مخططات ومناظير ثلاثية الأبعاد وتصميم داخلي، نطوّرها معك خطوة بخطوة." },
      { n: "03", time: "الأسابيع 10–24", title: "التراخيص", text: "تجهيز الخرائط وملفات الترخيص وتقديمها ومتابعتها حتى الموافقة." },
      { n: "04", time: "من الشهر 6", title: "التنفيذ والتسليم", text: "إشراف أسبوعي وتقارير مصوّرة حتى تستلم المفتاح بيدك." },
    ],
  },
  contact: {
    eyebrow: "تواصل معنا",
    title: "لديك أرض أو مبنى أو فكرة؟",
    text: "أخبرنا عنها. نردّ خلال يوم عمل واحد، والاستشارة الأولى مجانية.",
    phoneLabel: "هاتف وواتساب",
    phone: "[رقم الهاتف]",
    emailLabel: "البريد الإلكتروني",
    email: "[البريد الإلكتروني]",
    addressLabel: "المكتب · الأحد–الخميس 9:00–18:00",
    address: "[عنوان المكتب، المدينة]",
    whatsapp: "تواصل عبر واتساب",
    formTitle: "اطلب استشارة مجانية",
    form: {
      name: "الاسم الكامل",
      phone: "رقم الهاتف",
      service: "الخدمة",
      services: ["مشروع كامل", "التصميم المعماري", "التصميم الداخلي", "التراخيص وتصاريح البناء", "الخرائط ومخططات الموقع"],
      area: "مساحة الأرض / المبنى (م²)",
      message: "أخبرنا عن المشروع",
      submit: "أرسل الطلب",
      sent: "شكرًا لك — سنتواصل معك خلال يوم عمل واحد.",
    },
  },
  footer: {
    nav: [
      { label: "المكتب", href: "#studio" },
      { label: "الخدمات", href: "#services" },
      { label: "المشاريع", href: "#projects" },
      { label: "تواصل معنا", href: "#contact" },
      { label: "إنستغرام", href: "#contact" },
    ],
    copyright: "© 2026 باسم كيال، مهندس معماري",
    tagline: "أنيق · عصري · خالد",
  },
};
