import type { SiteContent } from "./types";

const ICONS = {
  architecture: "M6 34h28M10 34V14l10-8 10 8v20M16 34V22h8v12",
  interior: "M8 22h24v8H8zM11 30v4M29 30v4M11 22v-6a3 3 0 0 1 3-3h12a3 3 0 0 1 3 3v6",
  permits: "M11 5h13l7 7v23H11zM24 5v7h7M16 20h10M16 25h10M16 30h6",
  maps: "M5 10l10-4 10 4 10-4v24l-10 4-10-4-10 4zM15 6v24M25 10v24",
  supervision:
    "M8 35V9h10v26M18 16h14v19M4 35h32M12 14h2M12 20h2M12 26h2M23 22h4M23 28h4",
  licensed: "M5 14l6 6L23 8",
  model3d: "M14 4l9 5v10l-9 5-9-5V9zM14 14l9-5M14 14v10M14 14L5 9",
  siteVisits: "M4 8h20v14H4zM4 12h20M9 4v6M19 4v6",
  fixedFee: "M8 4h9l5 5v15H8zM17 4v5h5M12 15h6M12 19h6",
};

export const en: SiteContent = {
  meta: {
    title: "Basim Kayal Architect — Studio",
    description:
      "Survey maps, permits, architecture and interiors, all in one studio. Basim Kayal Architect takes your project from an empty plot to a finished home.",
  },
  nav: {
    studio: "Studio",
    services: "Services",
    projects: "Projects",
    process: "Process",
    contact: "Contact",
    cta: "Book a consultation",
    langLabel: "عربي",
    langHref: "/ar",
    menuLabel: "Menu",
  },
  brand: { name: "BASIM KAYAL", role: "ARCHITECT" },
  hero: {
    badge: "Accepting new projects for 2027",
    titleLead: "Spaces drawn with precision, ",
    titleAccent: "built to endure.",
    subtitle:
      "Survey maps, permits, architecture and interiors, all in one studio. Your project goes from an empty plot to a finished home with a single point of contact.",
    ctaPrimary: "Start your project",
    ctaSecondary: "View 240+ projects",
    stats: [
      { value: 18, suffix: "+", label: "Years of practice" },
      { value: 240, suffix: "+", label: "Projects delivered" },
      { value: 96, suffix: "%", label: "Permits approved first time" },
    ],
    model: { tag: "3D MODEL · VILLA 01", scale: "SCALE 1:100", elev: "ELEV. +7.20 M", gfa: "GFA 640 M²" },
    floatCard: {
      title: "VILLA 01",
      floorsLabel: "Floors",
      floors: "3",
      plotLabel: "Plot",
      plot: "1,150 m²",
      permitLabel: "Permit",
      permit: "Approved",
    },
  },
  marquee: [
    "Villas",
    "Residential buildings",
    "Interior design",
    "Survey maps",
    "Building permits",
    "Site supervision",
  ],
  studio: {
    eyebrow: "THE STUDIO",
    title: "One architect, from the first sketch to the final key.",
    text: "Basim Kayal designs homes and buildings inside and out, and handles everything between an idea and a finished building: site maps, drawings, licensing and supervision on site.",
    featured: { tag: "FEATURED PROJECT", name: "Hillside Villa", area: "640 m²", floors: "3", year: "2025" },
    cards: [
      { title: "Licensed architect", note: "Reg. no. [000000]", icon: ICONS.licensed },
      { title: "3D before you build", note: "Walk through every room", icon: ICONS.model3d },
      { title: "Weekly site visits", note: "With photo reports", icon: ICONS.siteVisits },
      { title: "Fixed-fee proposals", note: "No surprises later", icon: ICONS.fixedFee },
    ],
  },
  bigStats: {
    eyebrow: "BY THE NUMBERS",
    title: "Eighteen years of drawings, permits and finished homes.",
    updated: "Updated [month] 2026",
    stats: [
      { value: 85000, suffix: " m²", label: "Designed floor area", note: "Homes, buildings and interiors" },
      { value: 310, suffix: "+", label: "Permits and licences", note: "Prepared and followed to approval" },
      { value: 1200, suffix: "+", label: "Site visits", note: "Weekly supervision with photo reports" },
      { value: 98, suffix: "%", label: "Clients who return or refer", note: "Based on [client survey]" },
    ],
    mix: {
      title: "Project mix",
      note: "share of 240 projects",
      rows: [
        { label: "Private villas & homes", pct: 54, color: "var(--color-gold)" },
        { label: "Residential buildings", pct: 21, color: "var(--color-gold-soft)" },
        { label: "Interiors", pct: 15, color: "var(--color-gold-dust)" },
        { label: "Commercial & public", pct: 10, color: "#968870" },
      ],
      avgLabel: "Average permit time",
      avgValue: "11 weeks",
    },
  },
  services: {
    eyebrow: "SERVICES",
    title: "Everything your building needs.",
    text: "Take one service or the whole path. Each stage is prepared so the next one moves without delay.",
    timelineLabel: "Typical timeline",
    items: [
      {
        num: "01",
        title: "Architectural design",
        text: "Villas, homes and buildings, from the first concept sketch to full construction drawings.",
        items: ["Concept design", "Plans & elevations", "3D renders", "Construction set"],
        time: "6–12 weeks",
        icon: ICONS.architecture,
      },
      {
        num: "02",
        title: "Interior design",
        text: "Layouts, materials, lighting and furniture, designed together with the building.",
        items: ["Space planning", "Material boards", "Lighting plan", "Custom joinery"],
        time: "4–8 weeks",
        icon: ICONS.interior,
      },
      {
        num: "03",
        title: "Permits & licensing",
        text: "Files prepared, submitted and followed with the authorities until approval.",
        items: ["Building permit", "Additions", "Legalisation"],
        time: "8–14 weeks",
        icon: ICONS.permits,
      },
      {
        num: "04",
        title: "Maps & site plans",
        text: "Survey maps and plot studies that set the base for every decision.",
        items: ["Survey map", "Plot study", "Site plan"],
        time: "1–3 weeks",
        icon: ICONS.maps,
      },
      {
        num: "05",
        title: "Site supervision",
        text: "Weekly visits and follow-up with contractors, so the building matches the design.",
        items: ["Weekly visits", "Photo reports", "Handover"],
        time: "Until handover",
        icon: ICONS.supervision,
      },
    ],
  },
  projects: {
    eyebrow: "SELECTED WORK",
    title: "Projects",
    filters: [
      { key: "all", label: "All" },
      { key: "residential", label: "Residential" },
      { key: "interiors", label: "Interiors" },
      { key: "commercial", label: "Commercial" },
    ],
    areaLabel: "AREA",
    floorsLabel: "FLOORS",
    cityLabel: "CITY",
    yearLabel: "YEAR",
    photoPlaceholder: "[PROJECT PHOTO]",
    items: [
      { name: "Hillside Villa", catKey: "residential", cat: "Residential", city: "[City]", area: "640 m²", floors: "3", year: "2025", hasImage: true },
      { name: "Studio Kayal", catKey: "commercial", cat: "Commercial", city: "[City]", area: "180 m²", floors: "1", year: "2024", hasImage: true },
      { name: "Courtyard House", catKey: "residential", cat: "Residential", city: "[City]", area: "420 m²", floors: "2", year: "2024", hasImage: false },
      { name: "Stone Loft", catKey: "interiors", cat: "Interiors", city: "[City]", area: "210 m²", floors: "1", year: "2025", hasImage: false },
      { name: "Olive Grove Apartments", catKey: "residential", cat: "Residential", city: "[City]", area: "2,150 m²", floors: "5", year: "2023", hasImage: false },
      { name: "Cedar Clinic", catKey: "commercial", cat: "Commercial", city: "[City]", area: "560 m²", floors: "2", year: "2022", hasImage: false },
    ],
  },
  process: {
    eyebrow: "HOW WE WORK",
    title: "A clear path in four steps.",
    badge: "Average project: 9–14 months",
    steps: [
      { n: "01", time: "Week 1", title: "Consultation", text: "We visit the plot or building, listen to your needs and agree on scope, budget and fee." },
      { n: "02", time: "Weeks 2–10", title: "Concept & design", text: "Plans, 3D views and interiors, refined with you until every room feels right." },
      { n: "03", time: "Weeks 10–24", title: "Permits", text: "Maps and licensing files prepared, submitted and followed through to approval." },
      { n: "04", time: "Month 6+", title: "Build & handover", text: "Weekly site supervision and photo reports until the keys are in your hands." },
    ],
  },
  contact: {
    eyebrow: "CONTACT",
    title: "Have a plot, a building or an idea?",
    text: "Tell us about it. We reply within one working day, and the first consultation is free.",
    phoneLabel: "Phone & WhatsApp",
    phone: "+971 58 578 8678",
    emailLabel: "Email",
    email: "aliza22@gmail.com",
    addressLabel: "Studio · Sun–Thu, 9:00–18:00",
    address: "[OFFICE ADDRESS, CITY]",
    whatsapp: "Message on WhatsApp",
    formTitle: "Request a free consultation",
    form: {
      name: "Full name",
      phone: "Phone",
      service: "Service",
      services: ["Full project", "Architectural design", "Interior design", "Permits & licensing", "Maps & site plans"],
      area: "Plot / building size (m²)",
      message: "Tell us about the project",
      submit: "Send request",
      sent: "Thank you — we'll be in touch within one working day.",
    },
  },
  footer: {
    nav: [
      { label: "Studio", href: "#studio" },
      { label: "Services", href: "#services" },
      { label: "Projects", href: "#projects" },
      { label: "Contact", href: "#contact" },
      { label: "Instagram", href: "#contact" },
    ],
    copyright: "© 2026 Basim Kayal Architect",
    tagline: "CLEAN · MODERN · TIMELESS",
  },
};
